TempleCMS.Web/Controllers/ChurchesController.cs
using System.Security.Claims;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TempleCMS.Web.Data;
using TempleCMS.Web.Data.Services;
using TempleCMS.Web.Domain;
using TempleCMS.Web.Models;

namespace TempleCMS.Web.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class ChurchesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IFileService _fileService;

        public ChurchesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IFileService fileService)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _fileService = fileService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Churches.Include(c => c.Denomination).ToListAsync());
        }

        [Route("All")]
        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            return View(await _context.Churches.ToListAsync());
        }

        [Route("Create")]
        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Create")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChurchInputModel model)
        {
            if(ModelState.IsValid)
            {
                var church = new Church
                {
                    Name = model.ChurchName,
                    DenominationId = model.DenominationId
                };

                var user = new ApplicationUser
                {
                    Id = Guid.NewGuid().ToString(),
                    FullName = model.FullName,
                    UserName = model.Email, 
                    Email = model.Email
                };

                _context.Add(church);
                _context.SaveChanges();

                await _userManager.CreateAsync(user, model.Password);
                await _userManager.AddToRoleAsync(user, "Leadership");

                await _context.ChurchMembers.AddAsync(new ChurchMember
                {
                    Role = ChurchRole.Leader,
                    ChurchId = church.Id,
                    UserId = user.Id
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(All));
            }
            return View(model);
        }

        [Route("{id}/Details")]
        [AllowAnonymous]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var church = await _context.Churches
                .Include(c => c.Denomination)
                .Include(c => c.Members)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (church == null)
            {
                return NotFound();
            }
            
            return View(church);
        }

        [Route("{id}/Feed")]
        [AllowAnonymous]
        public async Task<IActionResult> Feed(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var church = await _context.Churches
                .Include(c => c.Denomination)
                .Include(c => c.Members)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (church == null)
            {
                return NotFound();
            }
            
            return View(church);
        }

        [Route("{id}/Join")]
        public async Task<IActionResult> Join(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var church = await _context.Churches
                .Include(c => c.Denomination)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (church == null)
            {
                return NotFound();
            }

            await _context.AddAsync(new ChurchMember
            {
                Role = ChurchRole.Laity,
                ChurchId = church.Id,
                UserId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value
            });
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Feed), new { id = church.Id });
        }
    
        [Route("{branch}/GetDenominations")]
        [AllowAnonymous]
        public async Task<JsonResult> GetDenominations(int branch)
        {
            return branch switch
            {
                0 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.Catholic).ToListAsync()),
                1 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.EasternOrthodox).ToListAsync()),
                2 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.OrientalOrthodox).ToListAsync()),
                3 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.Protestant).ToListAsync()),
                4 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.Unitarian).ToListAsync()),
                5 => new JsonResult(await _context.Denominations
                                        .Where(d => d.Branch == Branch.NonDenominational).ToListAsync()),
                _ => new JsonResult(new List<Denomination>().AsReadOnly()),
            };
        }

       private bool ChurchExists(long id)
    {
        return (_context.Churches?.Any(e => e.Id == id)).GetValueOrDefault();
    } 
    }
}

TempleCMS.Web/Views/Shared/Churches/_ChurchCard.cshtml
@model Church

<div class="col-12 col-sm-6 col-md-4 col-xxl-3">
    <div class="btn-reveal-trigger position-relative rounded-2 overflow-hidden p-4" style="height: 236px;">
        <div class="bg-holder" style="background-image: linear-gradient(180deg, rgba(0, 0, 0, 0) 39.41%, rgba(0, 0, 0, 0.4) 100%), url(/media/churches/@Model.Image)"></div>
        <div class="position-relative h-100 d-flex flex-column justify-content-between">
            <div class="d-flex justify-content-between align-items-center">
                <span class="badge badge-phoenix fs--2 light badge-phoenix-primary">@Model.Denomination!.Name</span>
                <div class="z-index-2">
                    <button class="btn btn-icon btn-reveal dropdown-toggle dropdown-caret-none transition-none" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent">
                        <span class="fas fa-ellipsis-v"></span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end py-2">
                        <a class="dropdown-item" href="#!">View</a>
                        <a class="dropdown-item" href="#!">Export</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="#!">Remove</a>
                    </div>
                </div>
            </div>
            <h3 class="text-white light fw-bold line-clamp-2">@Model.Name</h3>
        </div>
        <a class="stretched-link" asp-controller="Churches" asp-action="Details" asp-route-id="@Model.Id"></a>
    </div>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchDetailsCard.cshtml
@model Church

<div class="card mb-5">
    <div class="card-header hover-actions-trigger position-relative mb-7" style="min-height: 130px; ">
        <div class="bg-holder rounded-top"
            style="background-image: linear-gradient(0deg, #000000 -3%, rgba(0, 0, 0, 0) 83%), url(/media/churches/@Model.Image)">
            <input class="d-none" id="upload-feed-cover-image" type="file" />
            <label class="cover-image-file-input" for="upload-feed-cover-image"></label>
            <div class="hover-actions end-0 bottom-0 pe-1 pb-2 text-white">
                <span class="fa-solid fa-camera me-2 overlay-icon"> </span>
            </div>
        </div>
        <input class="d-none" id="upload-feed-porfile-picture" type="file" />
        @await Component.InvokeAsync("ChurchLeaderAvatar", new { churchId = Model.Id })
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <div class="d-flex flex-wrap mb-3 align-items-center">
                    <h3 class="me-2">@Model.Name</h3>
                    @* <span class="fw-normal fs-0"> - @Model.Denomination!.Name</span> *@
                </div>
                <div class="mb-3">
                    <div class="d-flex align-items-center flex-wrap">
                        <div class="d-flex me-4 mb-2">
                            <span class="fa-solid fa-user-group fs--2 me-2 me-lg-1 me-xl-2"></span>
                            <h6 class="d-inline-block mb-0">1297 <span class="fw-semi-bold">Followers</span></h6>
                        </div>
                        <div class="d-flex mb-2">
                            <span class="fa-solid fa-user-check fs--2 me-2 me-lg-1 me-xl-2"></span>
                            <h6 class="d-block d-xl-inline-block mb-0">
                                3971 <span class="fw-semi-bold">Following</span>
                            </h6>
                        </div>
                    </div>
                </div>
                <p class="fw-semi-bold mb-0">
                    Our Story
                    <a href="#!">
                        <span class="fa-solid fa-pencil fs--2 text-500 ms-3"></span>
                    </a>
                </p>
                <div class="text-700 mb-0">
                    @Html.Raw(HttpUtility.HtmlDecode(Model.Background.Truncate(135)))
                </div>
                @await Html.PartialAsync("Churches/_ChurchJoinButton")
            </div>
        </div>
    </div>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchFeedDonors.cshtml
<div class="mb-8 mt-6">
    <div class="d-flex pb-4 align-items-end">
        <h3 class="flex-1 mb-0">Donors</h3>
        <a class="fw-bold fs--1 me-4" href="#!">Donate</a>
        <a class="fw-bold fs--1" href="#!">See all</a>
    </div>
    <div class="d-flex py-3 align-items-center border-bottom border-dashed">
        <div class="me-2">
            <div class="avatar avatar-m status-online ">
                <img class="rounded-circle " src="~/assets/img/team/35.webp" alt="" />

            </div>
        </div><a class="text-decoration-none flex-1" href="../../apps/chat.html">
            <h5>Stanly Drinkwater</h5>
            <p class="text-700 fw-semi-bold fs--1 mb-0 lh-sm line-clamp-1">When you gonna pay me
                back, don’t leave me hanging</p>
        </a>
    </div>
    <div class="d-flex py-3 align-items-center border-bottom border-dashed">
        <div class="me-2">
            <div class="avatar avatar-m status-online ">
                <img class="rounded-circle " src="~/assets/img/team/30.webp" alt="" />

            </div>
        </div><a class="text-decoration-none flex-1" href="../../apps/chat.html">
            <h5>Milind Mikuja</h5>
            <p class="text-700 fw-semi-bold fs--1 mb-0 lh-sm line-clamp-1">But the mare fact that
                she said that makes</p>
        </a>
    </div>
    <div class="d-flex py-3 align-items-center border-bottom border-dashed">
        <div class="me-2">
            <div class="avatar avatar-m status-online ">
                <img class="rounded-circle avatar-placeholder" src="~/assets/img/team/avatar.webp"
                    alt="" />

            </div>
        </div><a class="text-decoration-none flex-1" href="../../apps/chat.html">
            <h5>Josef Stravinsky</h5>
            <p class="text-700 fw-semi-bold fs--1 mb-0 lh-sm line-clamp-1">Oi Cult.</p>
        </a>
    </div>
    <div class="d-flex py-3 align-items-center border-bottom border-dashed">
        <div class="me-2">
            <div class="avatar avatar-m status-online ">
                <img class="rounded-circle " src="~/assets/img/team/59.webp" alt="" />

            </div>
        </div>
        <a class="text-decoration-none flex-1" href="../../apps/chat.html">
            <h5>Martina scorcese</h5>
            <p class="text-700 fw-semi-bold fs--1 mb-0 lh-sm line-clamp-1">Thanks for that.
                Sincerely.</p>
        </a>
    </div>
    <div class="d-flex py-3 align-items-center border-bottom border-dashed">
        <div class="me-2">
            <div class="avatar avatar-m status-online ">
                <img class="rounded-circle " src="~/assets/img/team/57.webp" alt="" />
            </div>
        </div>
        <a class="text-decoration-none flex-1" href="../../apps/chat.html">
            <h5>Meekona Zikon</h5>
            <p class="text-700 fw-semi-bold fs--1 mb-0 lh-sm line-clamp-1">I am Outside, Come here,
                Lets smoke...</p>
        </a>
    </div>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchFeedEvents.cshtml
<div class="d-flex pb-4 border-bottom border-dashed border-300 align-items-end">
    <h3 class="flex-1 mb-0">Events</h3><a class="fw-bold fs--1" href="#!">See more</a>
</div>
<div class="py-3 border-bottom border-dashed">
    <div class="d-flex flex-between-center">
        <p class="text-warning fs--2 mb-0 fw-bold mb-1">MON, FEB 21- MARCH 23</p>
        <div class="btn-reveal-trigger">
            <button
                class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none d-flex btn-reveal"
                type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true"
                aria-expanded="false" data-bs-reference="parent">
                <span class="fas fa-ellipsis-h"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-end py-2">
                <a class="dropdown-item" href="#!">Edit</a>
                <a class="dropdown-item text-danger" href="#!">Delete</a>
                <a class="dropdown-item" href="#!">Download</a>
                <a class="dropdown-item" href="#!">Report abuse</a>
                </div>
        </div>
    </div><a class="hover-primary text-1000 fw-bold mb-2 line-clamp-1 me-5 lh-base" href="#!">Master
        Class on FILM Studies THESIS on Makers</a>
    <p class="text-800 fs--1 mb-2">Organized by <br /><a class="fw-bold text-primary"
            href="#!">IAFM- International Academy of Film and Media</a></p>
    <p class="fs--2 text-600">64 people going</p>
    <p class="fs--1 text-700 fw-bold mb-1"><span
            class="fa-solid fa-clock text-800 me-1"></span>12.30PM - 10PM</p>
    <p class="fs--1 text-700 fw-bold mb-0"><span
            class="fa-solid fa-map-marker-alt text-800 me-1"></span>Tavern on the Greend, New York
    </p>
</div>
<div class="py-3 border-bottom border-dashed">
    <div class="d-flex flex-between-center">
        <p class="text-warning fs--2 mb-0 fw-bold mb-1">MON, FEB 21- MARCH 23</p>
        <div class="btn-reveal-trigger">
            <button
                class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none d-flex btn-reveal"
                type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true"
                aria-expanded="false" data-bs-reference="parent"><span
                    class="fas fa-ellipsis-h"></span></button>
            <div class="dropdown-menu dropdown-menu-end py-2"><a class="dropdown-item"
                    href="#!">Edit</a><a class="dropdown-item text-danger" href="#!">Delete</a><a
                    class="dropdown-item" href="#!">Download</a><a class="dropdown-item"
                    href="#!">Report abuse</a></div>
        </div>
    </div><a class="hover-primary text-1000 fw-bold mb-2 line-clamp-1 me-5 lh-base" href="#!">Master
        Class on FILM Studies 'ANALYSIS of Cinema'</a>
    <p class="text-800 fs--1 mb-2">Organized by <br /><a class="fw-bold text-primary"
            href="#!">IAFM- International Academy of Film and Media</a></p>
    <p class="fs--2 text-600">64 people going</p>
    <p class="fs--1 text-700 fw-bold mb-1"><span
            class="fa-solid fa-clock text-800 me-1"></span>12.30PM - 10PM</p>
    <p class="fs--1 text-700 fw-bold mb-0"><span
            class="fa-solid fa-map-marker-alt text-800 me-1"></span>Tavern on the Greend, New York
    </p>
</div>
<div class="py-3 border-bottom border-dashed">
    <div class="d-flex flex-between-center">
        <p class="text-warning fs--2 mb-0 fw-bold mb-1">MON, FEB 21- MARCH 23</p>
        <div class="btn-reveal-trigger">
            <button
                class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none d-flex btn-reveal"
                type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true"
                aria-expanded="false" data-bs-reference="parent"><span
                    class="fas fa-ellipsis-h"></span></button>
            <div class="dropdown-menu dropdown-menu-end py-2"><a class="dropdown-item"
                    href="#!">Edit</a><a class="dropdown-item text-danger" href="#!">Delete</a><a
                    class="dropdown-item" href="#!">Download</a><a class="dropdown-item"
                    href="#!">Report abuse</a></div>
        </div>
    </div><a class="hover-primary text-1000 fw-bold mb-2 line-clamp-1 me-5 lh-base"
        href="#!">Witnessing History in Making Photographs</a>
    <p class="text-800 fs--1 mb-2">Organized by <br /><a class="fw-bold text-primary"
            href="#!">IAFM- International Academy of Film and Media</a></p>
    <p class="fs--2 text-600">64 people going</p>
    <p class="fs--1 text-700 fw-bold mb-1"><span
            class="fa-solid fa-clock text-800 me-1"></span>12.30PM - 10PM</p>
    <p class="fs--1 text-700 fw-bold mb-0"><span
            class="fa-solid fa-map-marker-alt text-800 me-1"></span>Tavern on the Greend, New York
    </p>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchFeedMenu.cshtml
@model Church

<div class="row g-0">
    <div class="col-6 border-1 border-bottom border-end py-2"> 
        <a class="btn btn-link ps-2 fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            href="#!">
            <span class="uil uil-comment-alt-share fs-2 me-2 mb-2 mb-xxl-0"></span>Feed
        </a>
    </div>
    <div class="col-6 border-1 border-bottom py-2">
        <a class="btn btn-link fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            asp-controller="Churches" asp-action="Details" asp-route-id="@Model.Id">
            <span class="uil uil-info-circle fs-2 me-2 mb-2 mb-xxl-0"></span>Details
        </a>
    </div>
    <div class="col-6 border-1 border-bottom border-end py-2">
        <a class="btn btn-link ps-2 fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            href="#!">
            <span class="uil uil-users-alt fs-2 me-2 mb-2 mb-xxl-0"></span>Members
        </a>
    </div>
    <div class="col-6 border-1 border-bottom py-2">
        <a 
            class="btn btn-link fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            href="#!">
            <span class="uil uil-heart fs-2 me-2 mb-2 mb-xxl-0"></span>Donate
        </a>
    </div>
    <div class="col-6 border-1 border-end py-2">
        <a
            class="btn btn-link ps-2 fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            href="#!">
            <span class="uil uil-calendar-alt fs-2 me-2 mb-2 mb-xxl-0"></span>Events
        </a>
    </div>
    <div class="col-6 border-1 py-2">
        <a
            class="btn btn-link fs-0 text-800 hover-primary fw-semi-bold d-flex flex-column d-xxl-inline-block"
            href="#!">
            <span class="uil uil-comment-image fs-2 me-2 mb-2 mb-xxl-0"></span>Media 
        </a>
    </div>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchFeedSide.cshtml
@model Church
<partial name="Churches/_ChurchDetailsCard"/>
<partial name="Churches/_ChurchFeedMenu"/>
<partial name="Churches/_ChurchFeedDonors"/>
<partial name="Churches/_ChurchFeedVideos"/>
<partial name="Churches/_ChurchFeedEvents"/>

TempleCMS.Web/Views/Shared/Churches/_ChurchFeedVideos.cshtml
<div class="mb-8">
    <div class="d-flex pb-4 align-items-end">
        <h3 class="flex-1 mb-0">Videos</h3>
        <a class="fw-bold fs--1" href="#!">See all</a>
    </div>
    <div class="row g-3">
        <div class="col-4">
            <a href="~/assets/img/gallery/11.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/11.png" alt="" />
            </a>
        </div>
        <div class="col-4">
            <a href="~/assets/img/gallery/12.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/12.png" alt="" />
            </a>
        </div>
        <div class="col-4">
            <a href="~/assets/img/gallery/13.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/13.png" alt="" />
            </a>
        </div>
        <div class="col-4">
            <a href="~/assets/img/gallery/14.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/14.png" alt="" />
            </a>
        </div>
        <div class="col-4">
            <a href="~/assets/img/gallery/15.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/15.png" alt="" />
            </a>
        </div>
        <div class="col-4">
            <a href="~/assets/img/gallery/16.png" data-gallery="gallery-photos">
                <img class="w-100 rounded-3" src="~/assets/img/gallery/16.png" alt="" />
            </a>
        </div>
    </div>
</div>

TempleCMS.Web/Views/Shared/Churches/_ChurchJoinButton.cshtml
@model Church
@inject SignInManager<ApplicationUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    @if (Model.Members.Any(c => c.UserId == User.FindFirst(ClaimTypes.NameIdentifier)!.Value))
    {
        <a href="#!" class="btn btn-primary w-100 disabled" tabindex="-1" role="button" aria-disabled="true">
            Join
        </a>

    }
    else
    {
        <a asp-controller="Churches" asp-action="Join" asp-route-id="@Model.Id" class="btn btn-primary w-100">
            Join
        </a>
    }
}
else
{
    <a asp-controller="Account" asp-action="Login" class="btn btn-primary w-100" role="button">
        Join
    </a>
}

TempleCMS.Web/Views/Shared/Churches/_ChurchTabList.cshtml
@model Church

<ul class="nav nav-underline deal-details scrollbar flex-nowrap w-100 pb-1 mb-3" id="myTab" role="tablist" style="overflow-y: hidden;">
    <li class="nav-item text-nowrap me-2" role="presentation">
        <a class="nav-link @Html.ActiveClass("ChurchManager", "Edit")" id="1-tab" asp-controller="ChurchManager" asp-action="Edit" asp-route-id="@Model.Id" role="tab" aria-controls="tab-1"> 
            Church
        </a>
    </li>
    <li class="nav-item text-nowrap me-2" role="presentation">
        <a class="nav-link @Html.ActiveClass("ChurchManager", "Image")" id="2-tab" asp-controller="ChurchManager" asp-action="Image" asp-route-id="@Model.Id" role="tab" aria-controls="tab-2"> 
            Image
        </a>
    </li>
    <li class="nav-item text-nowrap me-2" role="presentation">
        <a class="nav-link @Html.ActiveClass("ChurchManager", "Background")" id="3-tab" asp-controller="ChurchManager" asp-action="Background" asp-route-id="@Model.Id" role="tab" aria-controls="tab-3"> 
            Background
        </a>
    </li>
    <li class="nav-item text-nowrap me-2" role="presentation">
        <a class="nav-link @Html.ActiveClass("ChurchManager", "Message")" id="4-tab" asp-controller="ChurchManager" asp-action="Message" asp-route-id="@Model.Id" role="tab" aria-controls="tab-4"> 
            Message
        </a>
    </li>
    <li class="nav-item text-nowrap me-2" role="presentation">
        <a class="nav-link @Html.ActiveClass("ChurchManager", "Mission")" id="5-tab" asp-controller="ChurchManager" asp-action="Mission" asp-route-id="@Model.Id" role="tab" aria-controls="tab-5"> 
            Mission
        </a>
    </li>
</ul>